mkdir "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/Plug-ins"

#documentation
$SYSTEM_DEVELOPER_TOOLS/CpMac -p "$SOURCE_ROOT/Plug-ins/docs.html" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/Plug-ins/"
$SYSTEM_DEVELOPER_TOOLS/CpMac -p -r "$SOURCE_ROOT/Plug-ins/images" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/Plug-ins/"

#language stuff
$SYSTEM_DEVELOPER_TOOLS/CpMac -p "$SOURCE_ROOT/Plug-ins/Galactica Fonts" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/Plug-ins/"
$SYSTEM_DEVELOPER_TOOLS/CpMac -p "$SOURCE_ROOT/Plug-ins/Galactica Tutorial" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/Plug-ins/"
$SYSTEM_DEVELOPER_TOOLS/CpMac -p "$SOURCE_ROOT/Plug-ins/Galactica:en - cdrom" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/Plug-ins/"

#Art and music
$SYSTEM_DEVELOPER_TOOLS/CpMac -p "$SOURCE_ROOT/Galactica Art (Large)" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/"
$SYSTEM_DEVELOPER_TOOLS/CpMac -p "$SOURCE_ROOT/Galactica Music" "$BUILT_PRODUCTS_DIR/$EXECUTABLE_FOLDER_PATH/"

